// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ritocode.Modules.Workspaces.Persistence;

#nullable disable

namespace Ritocode.Modules.Workspaces.Persistence.Migrations
{
    [DbContext(typeof(WorkspacesDbContext))]
    [Migration("20260901072941_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("workspaces")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ritocode.Modules.Workspaces.Domain.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProblemVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_version_id");

                    b.Property<string>("SnapshotReference")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("snapshot_reference");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasIndex("ProblemVersionId")
                        .HasDatabaseName("ix_workspaces_problem_version_id");

                    b.HasIndex("UserId", "ProblemVersionId")
                        .HasDatabaseName("ix_workspaces_user_id_problem_version_id");

                    b.HasIndex("UserId", "UpdatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_workspaces_user_id_updated_at");

                    b.ToTable("workspaces", "workspaces", t =>
                        {
                            t.HasCheckConstraint("ck_workspaces_updated_not_before_created", "updated_at >= created_at");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
