// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ritocode.Modules.Attempts.Persistence;

#nullable disable

namespace Ritocode.Modules.Attempts.Persistence.Migrations
{
    [DbContext(typeof(AttemptsDbContext))]
    partial class AttemptsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("attempts")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ritocode.Modules.Attempts.Domain.Attempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .HasColumnType("jsonb")
                        .HasColumnName("answer");

                    b.Property<string>("ContentRevision")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_revision");

                    b.Property<bool>("CountsTowardProgress")
                        .HasColumnType("boolean")
                        .HasColumnName("counts_toward_progress");

                    b.Property<int?>("MaxScore")
                        .HasColumnType("integer")
                        .HasColumnName("max_score");

                    b.Property<string>("Result")
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("step");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("TaskSlug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("task_slug");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_attempts");

                    b.HasIndex("UserId", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_attempts_user_id_started_at");

                    b.HasIndex("UserId", "SubmittedAt")
                        .HasDatabaseName("ix_attempts_user_id_submitted_at");

                    b.HasIndex(new[] { "UserId", "TaskSlug" }, "ix_attempts_user_id_task_slug")
                        .HasDatabaseName("ix_attempts_user_id_task_slug");

                    b.HasIndex(new[] { "UserId", "TaskSlug" }, "ux_attempts_first_submission")
                        .IsUnique()
                        .HasDatabaseName("ux_attempts_first_submission")
                        .HasFilter("counts_toward_progress");

                    b.ToTable("attempts", "attempts", t =>
                        {
                            t.HasCheckConstraint("ck_attempts_counts_only_when_submitted", "NOT counts_toward_progress OR submitted_at IS NOT NULL");

                            t.HasCheckConstraint("ck_attempts_score_range", "score IS NULL OR (score >= 0 AND score <= max_score)");

                            t.HasCheckConstraint("ck_attempts_step", "\"step\" IN ('Diagnosis', 'Treatment')");

                            t.HasCheckConstraint("ck_attempts_submitted_whole", "(submitted_at IS NULL) = (content_revision IS NULL) AND (submitted_at IS NULL) = (answer IS NULL) AND (submitted_at IS NULL) = (result IS NULL) AND (submitted_at IS NULL) = (score IS NULL) AND (submitted_at IS NULL) = (max_score IS NULL)");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
