// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ritocode.Modules.Problems.Persistence;

#nullable disable

namespace Ritocode.Modules.Problems.Persistence.Migrations
{
    [DbContext(typeof(ProblemsDbContext))]
    partial class ProblemsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("problems")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ritocode.Modules.Problems.Domain.Problem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("difficulty");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("slug");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_problems");

                    b.HasIndex("Difficulty")
                        .HasDatabaseName("ix_problems_difficulty");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_problems_slug");

                    b.HasIndex("Tags")
                        .HasDatabaseName("ix_problems_tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");

                    b.ToTable("problems", "problems", t =>
                        {
                            t.HasCheckConstraint("ck_problems_difficulty", "\"difficulty\" IN ('Easy', 'Medium', 'Hard')");
                        });
                });

            modelBuilder.Entity("Ritocode.Modules.Problems.Domain.ProblemVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("SnapshotReference")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("snapshot_reference");

                    b.Property<string>("ValidatorConfig")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("validator_config");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_problem_versions");

                    b.HasIndex("ProblemId", "PublishedAt")
                        .HasDatabaseName("ix_problem_versions_problem_id_published_at")
                        .HasFilter("published_at IS NOT NULL");

                    b.HasIndex("ProblemId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_problem_versions_problem_id_version");

                    b.ToTable("problem_versions", "problems", t =>
                        {
                            t.HasCheckConstraint("ck_problem_versions_version_positive", "version >= 1");
                        });
                });

            modelBuilder.Entity("Ritocode.Modules.Problems.Domain.ProblemVersion", b =>
                {
                    b.HasOne("Ritocode.Modules.Problems.Domain.Problem", "Problem")
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_versions_problems_problem_id");

                    b.Navigation("Problem");
                });
#pragma warning restore 612, 618
        }
    }
}
