// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ritocode.Modules.Content.Persistence;

#nullable disable

namespace Ritocode.Modules.Content.Persistence.Migrations
{
    [DbContext(typeof(ContentDbContext))]
    partial class ContentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("content")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ritocode.Modules.Content.Persistence.StoredCard", b =>
                {
                    b.Property<string>("Slug")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("class");

                    b.Property<string>("ContentRevision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_revision");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at");

                    b.Property<string>("Texts")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("texts");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Slug")
                        .HasName("pk_cards");

                    b.ToTable("cards", "content", t =>
                        {
                            t.HasCheckConstraint("ck_cards_weight_range", "weight BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("Ritocode.Modules.Content.Persistence.StoredMaterial", b =>
                {
                    b.Property<string>("Slug")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<string>("ContentRevision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_revision");

                    b.Property<string>("Files")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("files");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("language");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("overview");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Slug")
                        .HasName("pk_materials");

                    b.ToTable("materials", "content");
                });

            modelBuilder.Entity("Ritocode.Modules.Content.Persistence.StoredTask", b =>
                {
                    b.Property<string>("Slug")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<string>("ContentRevision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_revision");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("difficulty");

                    b.Property<string>("Findings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("findings");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("material");

                    b.PrimitiveCollection<string[]>("Shortlist")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("shortlist");

                    b.Property<string>("Texts")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("texts");

                    b.Property<DateTimeOffset?>("UnpublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unpublished_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Slug")
                        .HasName("pk_tasks");

                    b.HasIndex("Material")
                        .HasDatabaseName("ix_tasks_material");

                    b.ToTable("tasks", "content", t =>
                        {
                            t.HasCheckConstraint("ck_tasks_difficulty", "difficulty IN ('easy', 'medium', 'hard')");
                        });
                });

            modelBuilder.Entity("Ritocode.Modules.Content.Persistence.StoredTaxonomy", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("ContentRevision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_revision");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("document");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_taxonomy");

                    b.ToTable("taxonomy", "content", t =>
                        {
                            t.HasCheckConstraint("ck_taxonomy_singleton", "id = 1");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
