// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ritocode.Modules.Submissions.Persistence;

#nullable disable

namespace Ritocode.Modules.Submissions.Persistence.Migrations
{
    [DbContext(typeof(SubmissionsDbContext))]
    partial class SubmissionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("submissions")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ritocode.Modules.Submissions.Domain.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_submissions");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_submissions_workspace_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_submissions_status_created_at")
                        .HasFilter("status IN ('Queued', 'Running')");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_submissions_user_id_created_at");

                    b.ToTable("submissions", "submissions", t =>
                        {
                            t.HasCheckConstraint("ck_submissions_completed_at_matches_status", "(status IN ('Completed', 'Failed')) = (completed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_submissions_score_range", "score IS NULL OR (score >= 0 AND score <= 100)");

                            t.HasCheckConstraint("ck_submissions_status", "\"status\" IN ('Queued', 'Running', 'Completed', 'Failed')");
                        });
                });

            modelBuilder.Entity("Ritocode.Modules.Submissions.Domain.SubmissionReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LogsReference")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("logs_reference");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<string>("ValidatorResults")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("validator_results");

                    b.HasKey("Id")
                        .HasName("pk_submission_reports");

                    b.HasIndex("SubmissionId")
                        .IsUnique()
                        .HasDatabaseName("ix_submission_reports_submission_id");

                    b.ToTable("submission_reports", "submissions");
                });

            modelBuilder.Entity("Ritocode.Modules.Submissions.Domain.SubmissionReport", b =>
                {
                    b.HasOne("Ritocode.Modules.Submissions.Domain.Submission", "Submission")
                        .WithOne()
                        .HasForeignKey("Ritocode.Modules.Submissions.Domain.SubmissionReport", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submission_reports_submissions_submission_id");

                    b.Navigation("Submission");
                });
#pragma warning restore 612, 618
        }
    }
}
